// Code generated by github.com/alanctgardner/gogen-avro. DO NOT EDIT.
/*
 * SOURCES:
 *     AnyArray.avsc
 *     ArrayOfBoolean.avsc
 *     ArrayOfDouble.avsc
 *     ArrayOfFloat.avsc
 *     ArrayOfInt.avsc
 *     ArrayOfLong.avsc
 *     ChannelIndexTypes.avsc
 *     ChannelMetadataRecord.avsc
 *     ChannelRangeInfo.avsc
 *     ChannelStatuses.avsc
 *     ChannelStreamingInfo.avsc
 *     DataFrame.avsc
 *     DataItem.avsc
 *     IndexDirections.avsc
 *     IndexMetadataRecord.avsc
 *     Roles.avsc
 *     StreamingStartIndex.avsc
 *     Contact.avsc
 *     DataAttribute.avsc
 *     DataValue.avsc
 *     MessageHeader.avsc
 *     DataObject.avsc
 *     GrowingObjectIndex.avsc
 *     NotificationRequestRecord.avsc
 *     ObjectChange.avsc
 *     ObjectChangeTypes.avsc
 *     Resource.avsc
 *     Protocols.avsc
 *     ServerCapabilities.avsc
 *     SupportedProtocol.avsc
 *     Version.avsc
 *     ChannelDataFrameSet.avsc
 *     ChannelMetadata.avsc
 *     RequestChannelData.avsc
 *     ChannelData.avsc
 *     ChannelDataChange.avsc
 *     ChannelDescribe.avsc
 *     ChannelMetadata.avsc
 *     ChannelRangeRequest.avsc
 *     ChannelRemove.avsc
 *     ChannelStatusChange.avsc
 *     ChannelStreamingStart.avsc
 *     ChannelStreamingStop.avsc
 *     Start.avsc
 *     Acknowledge.avsc
 *     CloseSession.avsc
 *     OpenSession.avsc
 *     ProtocolException.avsc
 *     RenewSecurityToken.avsc
 *     RequestSession.avsc
 *     DataArray.avsc
 *     GetDataArray.avsc
 *     GetDataArraySlice.avsc
 *     PutDataArray.avsc
 *     PutDataArraySlice.avsc
 *     GetResources.avsc
 *     GetResourcesResponse.avsc
 *     GrowingObjectDelete.avsc
 *     GrowingObjectDeleteRange.avsc
 *     GrowingObjectGet.avsc
 *     GrowingObjectGetRange.avsc
 *     GrowingObjectPut.avsc
 *     ObjectFragment.avsc
 *     DeleteObject.avsc
 *     GetObject.avsc
 *     Object.avsc
 *     PutObject.avsc
 *     CancelNotification.avsc
 *     ChangeNotification.avsc
 *     DeleteNotification.avsc
 *     NotificationRequest.avsc
 *     WMLS_AddToStore.avsc
 *     WMLS_DeleteFromStore.avsc
 *     WMLS_GetBaseMsg.avsc
 *     WMLS_GetCap.avsc
 *     WMLS_GetFromStore.avsc
 *     WMLS_GetVersion.avsc
 *     WMLS_UpdateInStore.avsc
 *     WMSL_AddToStoreResponse.avsc
 *     WMSL_DeleteFromStoreResponse.avsc
 *     WMSL_GetBaseMsgResponse.avsc
 *     WMSL_GetCapResponse.avsc
 *     WMSL_GetFromStoreResponse.avsc
 *     WMSL_GetVersionResponse.avsc
 *     WMSL_UpdateInStoreResponse.avsc
 */

package energistics

import (
	"io"
)

type ChannelData struct {
	Data []*DataItem
}

func DeserializeChannelData(r io.Reader) (*ChannelData, error) {
	return readChannelData(r)
}

func NewChannelData() *ChannelData {
	v := &ChannelData{
		Data: make([]*DataItem, 0),
	}

	return v
}

func (r *ChannelData) Schema() string {
	return "{\"fields\":[{\"name\":\"data\",\"type\":{\"items\":{\"fields\":[{\"name\":\"indexes\",\"type\":{\"items\":\"long\",\"type\":\"array\"}},{\"name\":\"channelId\",\"type\":\"long\"},{\"name\":\"value\",\"type\":{\"fields\":[{\"name\":\"item\",\"type\":[\"null\",\"double\",\"float\",\"int\",\"long\",\"string\",{\"fields\":[{\"name\":\"values\",\"type\":{\"items\":\"double\",\"type\":\"array\"}}],\"name\":\"ArrayOfDouble\",\"namespace\":\"Energistics.Datatypes\",\"type\":\"record\"},\"boolean\",\"bytes\"]}],\"name\":\"DataValue\",\"namespace\":\"Energistics.Datatypes\",\"type\":\"record\"}},{\"name\":\"valueAttributes\",\"type\":{\"items\":{\"fields\":[{\"name\":\"attributeId\",\"type\":\"int\"},{\"name\":\"attributeValue\",\"type\":\"Energistics.Datatypes.DataValue\"}],\"name\":\"DataAttribute\",\"namespace\":\"Energistics.Datatypes\",\"type\":\"record\"},\"type\":\"array\"}}],\"name\":\"DataItem\",\"namespace\":\"Energistics.Datatypes.ChannelData\",\"type\":\"record\"},\"type\":\"array\"}}],\"messageType\":\"3\",\"name\":\"ChannelData\",\"namespace\":\"Energistics.Protocol.ChannelStreaming\",\"protocol\":\"1\",\"protocolRoles\":\"producer,consumer\",\"senderRole\":\"producer\",\"type\":\"record\"}"
}

func (r *ChannelData) Serialize(w io.Writer) error {
	return writeChannelData(r, w)
}
